version: '3.8'
services:
  mysql:
    container_name: ${PROJECT_NAME}-${CONFIG}-mysql
    image: ${PROJECT_NAME}-${CONFIG}-mysql:latest
    build: ${CONFIG}/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME} 
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      TZ: UTC
    #tty: true
    #command: /bin/bash
    ports:
      - "3306:3306"
    volumes:
      - ${PROJECT_NAME}-db:/var/lib/mysql
    networks:
      - host_network

  apache:
    container_name: ${PROJECT_NAME}-${CONFIG}-apache
    image: ${PROJECT_NAME}-${CONFIG}-apache:latest
    build: ${CONFIG}/apache
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.nix.rule=Host(`nix.localhost`)
      - traefik.http.routers.nix.tls=${DOCKER_STACK_SSL}
    volumes:
      - ${PROJECT_PATH}/tmp/xdebug:/tmp/xdebug
      - ${PROJECT_PATH}/root:/var/www/html:delegated
    networks:
      - proxy
      - host_network
    command: /entrypoint.sh
    #tty: true
    #command: /bin/bash
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_OUTPUT_DIR=/tmp/xdebug
      - XDEBUG_START=yes    
  mailbox:
    container_name: ${PROJECT_NAME}-${CONFIG}-mailbox
    image: ${PROJECT_NAME}-${CONFIG}-mailbox:latest
    build: ${CONFIG}/mailbox
    platform: linux/amd64
    ports:
      - 1080:1080
    networks:
      - proxy
      - host_network

networks:
  host_network:
    driver: bridge
  proxy:
    external: true

volumes:
  nix-db:
    
